build:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script: 
    # Tool assembly version
    - sed -i "s;<AssemblyVersion>.*</AssemblyVersion>;<AssemblyVersion>$TOOL_VERSION</AssemblyVersion>;g" $TOOL_PROJECT
    # Lib assembly version
    - sed -i "s;<AssemblyVersion>.*</AssemblyVersion>;<AssemblyVersion>$LIB_VERSION</AssemblyVersion>;g" $LIB_PROJECT
    # Build packages
    - dotnet restore $TOOL_PROJECT
    - dotnet build -c Release 
    - dotnet pack -c Release --no-build
  artifacts:
    paths:
      - "**/bin/Release"
      - "**/obj/Release"
      - "**/*.nupkg"
    expire_in: 1 hour 
    